[[constraint]]
  name = "github.com/pulumi/pulumi"
  revision = "b9a0907161faf401da9b1cb7dab972449efebc12"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "f7064bdeddd27ee2a96d3556e8e7c9cc7689a1f5"
